# personnaliser le site à votre marque en remplaçant
# nom_intuition par le nom de votre intuition
# mon_equipe par le nom de votre équipe
# 
intuition: frigo_participatif
nom_equipe: 12caracteres
code_equipe: 1a

theme: jekyll-theme-dinky
